### ISSUE TITLE
MO Location Info Length is incorrect

### ISSUE THREAD

**Issue by miker1423** [gadomski/sbd-rs#10]
Hello, 
I tried to use your library for a little proyect but seems that the standard that I found at google does not represent the same as the one implemented here, I found the version [3.0](https://www.satcom.pro/upload/iblock/757/IRDM_IridiumSBDService_V3_DEVGUIDE_9Mar2012.pdf) from 2012, is there a newer version? My question is because of the fact that the IMEI is specified at the standard to be a sequences of 15 bytes but in ASCII encoding, but if I print the message as written to the cursor I see that the IMEI is represented as bytes (starting at position 9 as array-like indexed)
`1, 0, 34, 1, 0, 31, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 89, 208, 48, 0, 2, 0, 0` when it should be 
`1, 0, 34, 1, 0, 31, 0, 0, 0, 1, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 0, 0, 1, 0, 0, 89, 208, 48, 0, 2, 0, 0`

Thank you!

**Comment by gadomski** [comment]
Code was developed according to https://github.com/gadomski/sbd-rs/blob/e82295348474f3fb9751a301125a3790b3cc5bad/doc/Iridium%20Short%20Burst%20Data%20Service%20Developers%20Guide%20v3_0.pdf. The header is indeed stored as bytes, but there are expectations in the code that those bytes are valid `utf8`: https://github.com/gadomski/sbd-rs/blob/e82295348474f3fb9751a301125a3790b3cc5bad/src/mo/message.rs#L159-L176

Do you have some example data and/or code that show the problem?

**Comment by miker1423** [comment]
My bad, I understand now what I was doing wrong. Thank you!

**Comment by miker1423** [comment]
Sorry to reopen the issue, the length of MO Location Information should be 20 as shown in section 6.2.6 of the standard, am I right? I think the implementation has a 7 hard coded at https://github.com/gadomski/sbd-rs/blob/master/src/mo/information_element.rs#L138-L141

**Comment by gadomski** [comment]
No problem! Agreed, that hardcode is incorrect. I think I grabbed looked down instead of right in this table:

<img width="901" alt="Screen Shot 2021-07-29 at 11 57 50 AM" src="https://user-images.githubusercontent.com/58314/127541865-84c0290c-f82c-4c94-b75f-dda59c05ac4c.png">

I'll fix. Thanks for the catch.
