### ISSUE TITLE
Issues with imei when creating from header

### ISSUE THREAD

**Issue by jrjdavidson** [gadomski/sbd-rs#23]
kia ora,
thanks for the great package, seems to work great! I've been using this as a way to learn rust- so fairly new at this
I've run into an issue when writing a test. I've decided to create a synthetic header using the example like so:
```
        let header = InformationElement::Header(Header {
            auto_id: 1,
            imei: [0; 15],
            session_status: SessionStatus::Ok,
            momsn: 1,
            mtmsn: 0,
            time_of_session: Utc::now(),
        });
```
when i do so, the imei returns as :
`imei:<0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00><0x00>`
if I do the same with an acutal sbd file save to memory using the package, the imei returns as a number:, e.g.
`imei:300434064158300`
is it possible that there's an issue?

**Comment by gadomski** [comment]
That looks correct ... in your example, you're initializing the `imei` to fifteen zeros. To get a number like `300434064158300` you'll need to initialize that array w/ those (ASCII) values.

**Comment by jrjdavidson** [comment]
Ah i see. I was expecting to see the character 0, for that I would need to pass it's ASCII value. Thanks!
