### ISSUE TITLE
Error when the InformationElementType MobileOriginatedLocationInformation is present

### ISSUE THREAD

**Issue by johnthescienceguy** [gadomski/sbd-rs#9]
Hey Steve - when we deployed my we encountered this error.  Otherwise the basic service is now working.  Thanks.

My developer fixed it below:

When receiving an Iridium message containing a MobileOriginatedLocationInformation, the program throws an UnhandledInformationElements exception.

ERROR: Error when reading message: UnhandledInformationElements({MobileOriginatedLocationInformation: InformationElement { id: MobileOriginatedLocationInformation, length: 11, contents: [X, X, X, X, X, X, X, X, X, X, X] }})
(content values changed to X)

From what i've seen from the code, the program knows what a MobileOriginatedLocationInformation is, but doesn't do anything with it. Then, when the program sees that this element has not been handled, it throws the exception. The exception is thrown in Line 229, col 13 in mo.rs

Some quick fix I made to remove the bug (but does not handle the data, just removes it if present)

(start code)
    message.payload = payload.into_contents();
+
+  information_elements.remove(&InformationElementType::MobileOriginatedLocationInformation);
+  //TODO: Implement use of this variable

    if !information_elements.is_empty() {
        return Err(Error::UnhandledInformationElements(information_elements));
    }
(end code)

**Comment by gadomski** [comment]
Hi John, thanks for the report. I don't support location information elements (yet) because I didn't have any example data to work with. Is there any way to provide an example MO message that contains a location information element, that I can use to develop support? The message can be sent to my email that we communicated through before. Thanks!

**Comment by gadomski** [comment]
I just released v0.2.0 of the library, which can [handle messages with the `LocationInformation` information element](https://github.com/gadomski/sbd-rs/blob/master/src/mo/information_element.rs#L63). Try updating to this version and see if it fixes your issue?

I could still use an example message with the `LocationInformation` information element so I can parse the information inside the IE.

**Comment by gadomski** [comment]
@johnthescienceguy hopefully v0.2.0 allows you to receive your location-enabled sbd messages. As I haven't heard from you in a week or so, I'll close this issue. Please re-open if:

- v0.2.0 doesn't fix your problem, or
- you're able to provide a sbd message with the LocationInformation information element, that I can use to develop explicit support in this library.

Thanks!
